//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.iso20022.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorporateActionChangeType1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CorporateActionChangeType1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BERE"/>
 *     &lt;enumeration value="CERT"/>
 *     &lt;enumeration value="DEPH"/>
 *     &lt;enumeration value="GPPH"/>
 *     &lt;enumeration value="GTGP"/>
 *     &lt;enumeration value="GTPH"/>
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="PHDE"/>
 *     &lt;enumeration value="REBE"/>
 *     &lt;enumeration value="TERM"/>
 *     &lt;enumeration value="DECI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CorporateActionChangeType1Code")
@XmlEnum
public enum CorporateActionChangeType1Code {

    BERE,
    CERT,
    DEPH,
    GPPH,
    GTGP,
    GTPH,
    NAME,
    PHDE,
    REBE,
    TERM,
    DECI;

    public String value() {
        return name();
    }

    public static CorporateActionChangeType1Code fromValue(String v) {
        return valueOf(v);
    }

}
