//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.iso20022.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MeetingInstructionStatus_QNAME = new QName("", "MeetingInstructionStatus");
    private final static QName _MeetingNotification_QNAME = new QName("", "MeetingNotification");
    private final static QName _MeetingResultDissemination_QNAME = new QName("", "MeetingResultDissemination");
    private final static QName _MessageReject_QNAME = new QName("", "MessageReject");
    private final static QName _SystemEventNotification_QNAME = new QName("", "SystemEventNotification");
    private final static QName _MeetingInstruction_QNAME = new QName("", "MeetingInstruction");
    private final static QName _MeetingCancellation_QNAME = new QName("", "MeetingCancellation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XtnsnMeetingNotification }
     * 
     */
    public XtnsnMeetingNotification createXtnsnMeetingNotification() {
        return new XtnsnMeetingNotification();
    }

    /**
     * Create an instance of {@link XtnsnMeetingResultDissemination }
     * 
     */
    public XtnsnMeetingResultDissemination createXtnsnMeetingResultDissemination() {
        return new XtnsnMeetingResultDissemination();
    }

    /**
     * Create an instance of {@link XtnsnMeetingCancellation }
     * 
     */
    public XtnsnMeetingCancellation createXtnsnMeetingCancellation() {
        return new XtnsnMeetingCancellation();
    }

    /**
     * Create an instance of {@link XtnsnMeetingInstruction }
     * 
     */
    public XtnsnMeetingInstruction createXtnsnMeetingInstruction() {
        return new XtnsnMeetingInstruction();
    }

    /**
     * Create an instance of {@link MeetingInstructionStatus }
     * 
     */
    public MeetingInstructionStatus createMeetingInstructionStatus() {
        return new MeetingInstructionStatus();
    }

    /**
     * Create an instance of {@link MeetingNotification }
     * 
     */
    public MeetingNotification createMeetingNotification() {
        return new MeetingNotification();
    }

    /**
     * Create an instance of {@link MeetingResultDissemination }
     * 
     */
    public MeetingResultDissemination createMeetingResultDissemination() {
        return new MeetingResultDissemination();
    }

    /**
     * Create an instance of {@link SystemEventNotification }
     * 
     */
    public SystemEventNotification createSystemEventNotification() {
        return new SystemEventNotification();
    }

    /**
     * Create an instance of {@link MessageReject }
     * 
     */
    public MessageReject createMessageReject() {
        return new MessageReject();
    }

    /**
     * Create an instance of {@link MeetingInstruction }
     * 
     */
    public MeetingInstruction createMeetingInstruction() {
        return new MeetingInstruction();
    }

    /**
     * Create an instance of {@link MeetingCancellation }
     * 
     */
    public MeetingCancellation createMeetingCancellation() {
        return new MeetingCancellation();
    }

    /**
     * Create an instance of {@link PriceFormat29Choice }
     * 
     */
    public PriceFormat29Choice createPriceFormat29Choice() {
        return new PriceFormat29Choice();
    }

    /**
     * Create an instance of {@link PriceFormat20Choice }
     * 
     */
    public PriceFormat20Choice createPriceFormat20Choice() {
        return new PriceFormat20Choice();
    }

    /**
     * Create an instance of {@link DateAndDateTimeChoice }
     * 
     */
    public DateAndDateTimeChoice createDateAndDateTimeChoice() {
        return new DateAndDateTimeChoice();
    }

    /**
     * Create an instance of {@link CorporateActionPrice38 }
     * 
     */
    public CorporateActionPrice38 createCorporateActionPrice38() {
        return new CorporateActionPrice38();
    }

    /**
     * Create an instance of {@link MeetingReference4 }
     * 
     */
    public MeetingReference4 createMeetingReference4() {
        return new MeetingReference4();
    }

    /**
     * Create an instance of {@link CancellationProcessingStatus1 }
     * 
     */
    public CancellationProcessingStatus1 createCancellationProcessingStatus1() {
        return new CancellationProcessingStatus1();
    }

    /**
     * Create an instance of {@link MeetingReference5 }
     * 
     */
    public MeetingReference5 createMeetingReference5() {
        return new MeetingReference5();
    }

    /**
     * Create an instance of {@link CorporateActionNarrative20 }
     * 
     */
    public CorporateActionNarrative20 createCorporateActionNarrative20() {
        return new CorporateActionNarrative20();
    }

    /**
     * Create an instance of {@link AdditionalRights1 }
     * 
     */
    public AdditionalRights1 createAdditionalRights1() {
        return new AdditionalRights1();
    }

    /**
     * Create an instance of {@link AttendanceCard2 }
     * 
     */
    public AttendanceCard2 createAttendanceCard2() {
        return new AttendanceCard2();
    }

    /**
     * Create an instance of {@link CorporateActionNarrative24 }
     * 
     */
    public CorporateActionNarrative24 createCorporateActionNarrative24() {
        return new CorporateActionNarrative24();
    }

    /**
     * Create an instance of {@link DateFormat2Choice }
     * 
     */
    public DateFormat2Choice createDateFormat2Choice() {
        return new DateFormat2Choice();
    }

    /**
     * Create an instance of {@link AmountAndQuantityRatio2 }
     * 
     */
    public AmountAndQuantityRatio2 createAmountAndQuantityRatio2() {
        return new AmountAndQuantityRatio2();
    }

    /**
     * Create an instance of {@link DateCode11Choice }
     * 
     */
    public DateCode11Choice createDateCode11Choice() {
        return new DateCode11Choice();
    }

    /**
     * Create an instance of {@link RateType6Choice }
     * 
     */
    public RateType6Choice createRateType6Choice() {
        return new RateType6Choice();
    }

    /**
     * Create an instance of {@link RateType10Choice }
     * 
     */
    public RateType10Choice createRateType10Choice() {
        return new RateType10Choice();
    }

    /**
     * Create an instance of {@link MarketIdentification3Choice }
     * 
     */
    public MarketIdentification3Choice createMarketIdentification3Choice() {
        return new MarketIdentification3Choice();
    }

    /**
     * Create an instance of {@link MeetingInstructionStatusV04 }
     * 
     */
    public MeetingInstructionStatusV04 createMeetingInstructionStatusV04() {
        return new MeetingInstructionStatusV04();
    }

    /**
     * Create an instance of {@link Entitlement1Choice }
     * 
     */
    public Entitlement1Choice createEntitlement1Choice() {
        return new Entitlement1Choice();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link EntitlementAssessment2 }
     * 
     */
    public EntitlementAssessment2 createEntitlementAssessment2() {
        return new EntitlementAssessment2();
    }

    /**
     * Create an instance of {@link DateCode4Choice }
     * 
     */
    public DateCode4Choice createDateCode4Choice() {
        return new DateCode4Choice();
    }

    /**
     * Create an instance of {@link XtnsnAttachment }
     * 
     */
    public XtnsnAttachment createXtnsnAttachment() {
        return new XtnsnAttachment();
    }

    /**
     * Create an instance of {@link BranchData2 }
     * 
     */
    public BranchData2 createBranchData2() {
        return new BranchData2();
    }

    /**
     * Create an instance of {@link VoteMethods2 }
     * 
     */
    public VoteMethods2 createVoteMethods2() {
        return new VoteMethods2();
    }

    /**
     * Create an instance of {@link NetDividendRateFormat9Choice }
     * 
     */
    public NetDividendRateFormat9Choice createNetDividendRateFormat9Choice() {
        return new NetDividendRateFormat9Choice();
    }

    /**
     * Create an instance of {@link RateFormat7Choice }
     * 
     */
    public RateFormat7Choice createRateFormat7Choice() {
        return new RateFormat7Choice();
    }

    /**
     * Create an instance of {@link Participation3 }
     * 
     */
    public Participation3 createParticipation3() {
        return new Participation3();
    }

    /**
     * Create an instance of {@link AdditionalRightCode1Choice }
     * 
     */
    public AdditionalRightCode1Choice createAdditionalRightCode1Choice() {
        return new AdditionalRightCode1Choice();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification5 createBranchAndFinancialInstitutionIdentification5() {
        return new BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link AdditionalStatus2 }
     * 
     */
    public AdditionalStatus2 createAdditionalStatus2() {
        return new AdditionalStatus2();
    }

    /**
     * Create an instance of {@link SignatureEnvelope }
     * 
     */
    public SignatureEnvelope createSignatureEnvelope() {
        return new SignatureEnvelope();
    }

    /**
     * Create an instance of {@link AdditionalStatus1 }
     * 
     */
    public AdditionalStatus1 createAdditionalStatus1() {
        return new AdditionalStatus1();
    }

    /**
     * Create an instance of {@link XtnsnVoteAdditionalRequirements }
     * 
     */
    public XtnsnVoteAdditionalRequirements createXtnsnVoteAdditionalRequirements() {
        return new XtnsnVoteAdditionalRequirements();
    }

    /**
     * Create an instance of {@link GenericIdentification5 }
     * 
     */
    public GenericIdentification5 createGenericIdentification5() {
        return new GenericIdentification5();
    }

    /**
     * Create an instance of {@link GenericIdentification4 }
     * 
     */
    public GenericIdentification4 createGenericIdentification4() {
        return new GenericIdentification4();
    }

    /**
     * Create an instance of {@link GenericIdentification1 }
     * 
     */
    public GenericIdentification1 createGenericIdentification1() {
        return new GenericIdentification1();
    }

    /**
     * Create an instance of {@link TaxCreditRateFormat5Choice }
     * 
     */
    public TaxCreditRateFormat5Choice createTaxCreditRateFormat5Choice() {
        return new TaxCreditRateFormat5Choice();
    }

    /**
     * Create an instance of {@link CorporateActionNarrative11 }
     * 
     */
    public CorporateActionNarrative11 createCorporateActionNarrative11() {
        return new CorporateActionNarrative11();
    }

    /**
     * Create an instance of {@link ProcessingPosition1Choice }
     * 
     */
    public ProcessingPosition1Choice createProcessingPosition1Choice() {
        return new ProcessingPosition1Choice();
    }

    /**
     * Create an instance of {@link MessageReference }
     * 
     */
    public MessageReference createMessageReference() {
        return new MessageReference();
    }

    /**
     * Create an instance of {@link Instruction2 }
     * 
     */
    public Instruction2 createInstruction2() {
        return new Instruction2();
    }

    /**
     * Create an instance of {@link AmountPricePerFinancialInstrumentQuantity3 }
     * 
     */
    public AmountPricePerFinancialInstrumentQuantity3 createAmountPricePerFinancialInstrumentQuantity3() {
        return new AmountPricePerFinancialInstrumentQuantity3();
    }

    /**
     * Create an instance of {@link MeetingContactPerson1 }
     * 
     */
    public MeetingContactPerson1 createMeetingContactPerson1() {
        return new MeetingContactPerson1();
    }

    /**
     * Create an instance of {@link CorporateActionEventReference1Choice }
     * 
     */
    public CorporateActionEventReference1Choice createCorporateActionEventReference1Choice() {
        return new CorporateActionEventReference1Choice();
    }

    /**
     * Create an instance of {@link InstructionProcessingStatus1 }
     * 
     */
    public InstructionProcessingStatus1 createInstructionProcessingStatus1() {
        return new InstructionProcessingStatus1();
    }

    /**
     * Create an instance of {@link OptionStyle4Choice }
     * 
     */
    public OptionStyle4Choice createOptionStyle4Choice() {
        return new OptionStyle4Choice();
    }

    /**
     * Create an instance of {@link RateAndAmountFormat15Choice }
     * 
     */
    public RateAndAmountFormat15Choice createRateAndAmountFormat15Choice() {
        return new RateAndAmountFormat15Choice();
    }

    /**
     * Create an instance of {@link InstructionStatus3Choice }
     * 
     */
    public InstructionStatus3Choice createInstructionStatus3Choice() {
        return new InstructionStatus3Choice();
    }

    /**
     * Create an instance of {@link Vote2Choice }
     * 
     */
    public Vote2Choice createVote2Choice() {
        return new Vote2Choice();
    }

    /**
     * Create an instance of {@link DateFormat18Choice }
     * 
     */
    public DateFormat18Choice createDateFormat18Choice() {
        return new DateFormat18Choice();
    }

    /**
     * Create an instance of {@link MeetingCancellationReason2 }
     * 
     */
    public MeetingCancellationReason2 createMeetingCancellationReason2() {
        return new MeetingCancellationReason2();
    }

    /**
     * Create an instance of {@link PriceFormat19Choice }
     * 
     */
    public PriceFormat19Choice createPriceFormat19Choice() {
        return new PriceFormat19Choice();
    }

    /**
     * Create an instance of {@link IssuerAgent1 }
     * 
     */
    public IssuerAgent1 createIssuerAgent1() {
        return new IssuerAgent1();
    }

    /**
     * Create an instance of {@link Party10Choice }
     * 
     */
    public Party10Choice createParty10Choice() {
        return new Party10Choice();
    }

    /**
     * Create an instance of {@link RatioFormat12Choice }
     * 
     */
    public RatioFormat12Choice createRatioFormat12Choice() {
        return new RatioFormat12Choice();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link IntermediateSecuritiesDistributionTypeFormat9Choice }
     * 
     */
    public IntermediateSecuritiesDistributionTypeFormat9Choice createIntermediateSecuritiesDistributionTypeFormat9Choice() {
        return new IntermediateSecuritiesDistributionTypeFormat9Choice();
    }

    /**
     * Create an instance of {@link DateFormat3Choice }
     * 
     */
    public DateFormat3Choice createDateFormat3Choice() {
        return new DateFormat3Choice();
    }

    /**
     * Create an instance of {@link NonEligibleProceedsIndicator1Choice }
     * 
     */
    public NonEligibleProceedsIndicator1Choice createNonEligibleProceedsIndicator1Choice() {
        return new NonEligibleProceedsIndicator1Choice();
    }

    /**
     * Create an instance of {@link LongPostalAddress2Choice }
     * 
     */
    public LongPostalAddress2Choice createLongPostalAddress2Choice() {
        return new LongPostalAddress2Choice();
    }

    /**
     * Create an instance of {@link DividendTypeFormat3Choice }
     * 
     */
    public DividendTypeFormat3Choice createDividendTypeFormat3Choice() {
        return new DividendTypeFormat3Choice();
    }

    /**
     * Create an instance of {@link Period3Choice }
     * 
     */
    public Period3Choice createPeriod3Choice() {
        return new Period3Choice();
    }

    /**
     * Create an instance of {@link MeetingCancellationV04 }
     * 
     */
    public MeetingCancellationV04 createMeetingCancellationV04() {
        return new MeetingCancellationV04();
    }

    /**
     * Create an instance of {@link FinancialInstrumentAttributes34 }
     * 
     */
    public FinancialInstrumentAttributes34 createFinancialInstrumentAttributes34() {
        return new FinancialInstrumentAttributes34();
    }

    /**
     * Create an instance of {@link RateTypeAndAmountAndStatus3 }
     * 
     */
    public RateTypeAndAmountAndStatus3 createRateTypeAndAmountAndStatus3() {
        return new RateTypeAndAmountAndStatus3();
    }

    /**
     * Create an instance of {@link ForeignExchangeTerms19 }
     * 
     */
    public ForeignExchangeTerms19 createForeignExchangeTerms19() {
        return new ForeignExchangeTerms19();
    }

    /**
     * Create an instance of {@link Quantity6Choice }
     * 
     */
    public Quantity6Choice createQuantity6Choice() {
        return new Quantity6Choice();
    }

    /**
     * Create an instance of {@link ForeignExchangeTerms13 }
     * 
     */
    public ForeignExchangeTerms13 createForeignExchangeTerms13() {
        return new ForeignExchangeTerms13();
    }

    /**
     * Create an instance of {@link Vote4 }
     * 
     */
    public Vote4 createVote4() {
        return new Vote4();
    }

    /**
     * Create an instance of {@link Vote5 }
     * 
     */
    public Vote5 createVote5() {
        return new Vote5();
    }

    /**
     * Create an instance of {@link Resolution2 }
     * 
     */
    public Resolution2 createResolution2() {
        return new Resolution2();
    }

    /**
     * Create an instance of {@link Vote3 }
     * 
     */
    public Vote3 createVote3() {
        return new Vote3();
    }

    /**
     * Create an instance of {@link RateTypeAndAmountAndStatus5 }
     * 
     */
    public RateTypeAndAmountAndStatus5 createRateTypeAndAmountAndStatus5() {
        return new RateTypeAndAmountAndStatus5();
    }

    /**
     * Create an instance of {@link RateTypeAndAmountAndStatus6 }
     * 
     */
    public RateTypeAndAmountAndStatus6 createRateTypeAndAmountAndStatus6() {
        return new RateTypeAndAmountAndStatus6();
    }

    /**
     * Create an instance of {@link TaxableIncomePerShareCalculatedFormat1Choice }
     * 
     */
    public TaxableIncomePerShareCalculatedFormat1Choice createTaxableIncomePerShareCalculatedFormat1Choice() {
        return new TaxableIncomePerShareCalculatedFormat1Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link RatioFormat11Choice }
     * 
     */
    public RatioFormat11Choice createRatioFormat11Choice() {
        return new RatioFormat11Choice();
    }

    /**
     * Create an instance of {@link AmendInformation1 }
     * 
     */
    public AmendInformation1 createAmendInformation1() {
        return new AmendInformation1();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAnd13DecimalAmount }
     * 
     */
    public ActiveCurrencyAnd13DecimalAmount createActiveCurrencyAnd13DecimalAmount() {
        return new ActiveCurrencyAnd13DecimalAmount();
    }

    /**
     * Create an instance of {@link AmendInformation2 }
     * 
     */
    public AmendInformation2 createAmendInformation2() {
        return new AmendInformation2();
    }

    /**
     * Create an instance of {@link SecurityIdentification11 }
     * 
     */
    public SecurityIdentification11 createSecurityIdentification11() {
        return new SecurityIdentification11();
    }

    /**
     * Create an instance of {@link RateDetails10 }
     * 
     */
    public RateDetails10 createRateDetails10() {
        return new RateDetails10();
    }

    /**
     * Create an instance of {@link RateAndAmountFormat12Choice }
     * 
     */
    public RateAndAmountFormat12Choice createRateAndAmountFormat12Choice() {
        return new RateAndAmountFormat12Choice();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link DateFormat20Choice }
     * 
     */
    public DateFormat20Choice createDateFormat20Choice() {
        return new DateFormat20Choice();
    }

    /**
     * Create an instance of {@link FinancialInstrumentQuantity19Choice }
     * 
     */
    public FinancialInstrumentQuantity19Choice createFinancialInstrumentQuantity19Choice() {
        return new FinancialInstrumentQuantity19Choice();
    }

    /**
     * Create an instance of {@link DocumentMtngRsltDssmntn }
     * 
     */
    public DocumentMtngRsltDssmntn createDocumentMtngRsltDssmntn() {
        return new DocumentMtngRsltDssmntn();
    }

    /**
     * Create an instance of {@link MeetingTypeClassification1Choice }
     * 
     */
    public MeetingTypeClassification1Choice createMeetingTypeClassification1Choice() {
        return new MeetingTypeClassification1Choice();
    }

    /**
     * Create an instance of {@link SecurityIdentification14 }
     * 
     */
    public SecurityIdentification14 createSecurityIdentification14() {
        return new SecurityIdentification14();
    }

    /**
     * Create an instance of {@link CorporateActionChangeTypeFormat1Choice }
     * 
     */
    public CorporateActionChangeTypeFormat1Choice createCorporateActionChangeTypeFormat1Choice() {
        return new CorporateActionChangeTypeFormat1Choice();
    }

    /**
     * Create an instance of {@link InterestRateUsedForPaymentFormat5Choice }
     * 
     */
    public InterestRateUsedForPaymentFormat5Choice createInterestRateUsedForPaymentFormat5Choice() {
        return new InterestRateUsedForPaymentFormat5Choice();
    }

    /**
     * Create an instance of {@link DateCode10Choice }
     * 
     */
    public DateCode10Choice createDateCode10Choice() {
        return new DateCode10Choice();
    }

    /**
     * Create an instance of {@link MeetingNotice3 }
     * 
     */
    public MeetingNotice3 createMeetingNotice3() {
        return new MeetingNotice3();
    }

    /**
     * Create an instance of {@link Proxy4 }
     * 
     */
    public Proxy4 createProxy4() {
        return new Proxy4();
    }

    /**
     * Create an instance of {@link MeetingNotificationV04 }
     * 
     */
    public MeetingNotificationV04 createMeetingNotificationV04() {
        return new MeetingNotificationV04();
    }

    /**
     * Create an instance of {@link Proxy3 }
     * 
     */
    public Proxy3 createProxy3() {
        return new Proxy3();
    }

    /**
     * Create an instance of {@link OptionAvailabilityStatus1Choice }
     * 
     */
    public OptionAvailabilityStatus1Choice createOptionAvailabilityStatus1Choice() {
        return new OptionAvailabilityStatus1Choice();
    }

    /**
     * Create an instance of {@link HoldingBalance5 }
     * 
     */
    public HoldingBalance5 createHoldingBalance5() {
        return new HoldingBalance5();
    }

    /**
     * Create an instance of {@link HoldingBalance6 }
     * 
     */
    public HoldingBalance6 createHoldingBalance6() {
        return new HoldingBalance6();
    }

    /**
     * Create an instance of {@link XtnsnSharesDenominator }
     * 
     */
    public XtnsnSharesDenominator createXtnsnSharesDenominator() {
        return new XtnsnSharesDenominator();
    }

    /**
     * Create an instance of {@link SecurityPosition6 }
     * 
     */
    public SecurityPosition6 createSecurityPosition6() {
        return new SecurityPosition6();
    }

    /**
     * Create an instance of {@link UnitOrFaceAmount1Choice }
     * 
     */
    public UnitOrFaceAmount1Choice createUnitOrFaceAmount1Choice() {
        return new UnitOrFaceAmount1Choice();
    }

    /**
     * Create an instance of {@link CancellationStatus2Choice }
     * 
     */
    public CancellationStatus2Choice createCancellationStatus2Choice() {
        return new CancellationStatus2Choice();
    }

    /**
     * Create an instance of {@link NotificationStatus1 }
     * 
     */
    public NotificationStatus1 createNotificationStatus1() {
        return new NotificationStatus1();
    }

    /**
     * Create an instance of {@link ContactIdentification1 }
     * 
     */
    public ContactIdentification1 createContactIdentification1() {
        return new ContactIdentification1();
    }

    /**
     * Create an instance of {@link CashAccountIdentification5Choice }
     * 
     */
    public CashAccountIdentification5Choice createCashAccountIdentification5Choice() {
        return new CashAccountIdentification5Choice();
    }

    /**
     * Create an instance of {@link SafekeepingPlaceFormatChoice }
     * 
     */
    public SafekeepingPlaceFormatChoice createSafekeepingPlaceFormatChoice() {
        return new SafekeepingPlaceFormatChoice();
    }

    /**
     * Create an instance of {@link DateFormat16Choice }
     * 
     */
    public DateFormat16Choice createDateFormat16Choice() {
        return new DateFormat16Choice();
    }

    /**
     * Create an instance of {@link EligiblePosition3 }
     * 
     */
    public EligiblePosition3 createEligiblePosition3() {
        return new EligiblePosition3();
    }

    /**
     * Create an instance of {@link CorporateActionOption51 }
     * 
     */
    public CorporateActionOption51 createCorporateActionOption51() {
        return new CorporateActionOption51();
    }

    /**
     * Create an instance of {@link RateStatus1Choice }
     * 
     */
    public RateStatus1Choice createRateStatus1Choice() {
        return new RateStatus1Choice();
    }

    /**
     * Create an instance of {@link CorporateActionEventStageFormat3Choice }
     * 
     */
    public CorporateActionEventStageFormat3Choice createCorporateActionEventStageFormat3Choice() {
        return new CorporateActionEventStageFormat3Choice();
    }

    /**
     * Create an instance of {@link FinancialInstrumentQuantity1Choice }
     * 
     */
    public FinancialInstrumentQuantity1Choice createFinancialInstrumentQuantity1Choice() {
        return new FinancialInstrumentQuantity1Choice();
    }

    /**
     * Create an instance of {@link BusinessApplicationHeader1 }
     * 
     */
    public BusinessApplicationHeader1 createBusinessApplicationHeader1() {
        return new BusinessApplicationHeader1();
    }

    /**
     * Create an instance of {@link PriceRateOrAmountChoice }
     * 
     */
    public PriceRateOrAmountChoice createPriceRateOrAmountChoice() {
        return new PriceRateOrAmountChoice();
    }

    /**
     * Create an instance of {@link Admi00200101 }
     * 
     */
    public Admi00200101 createAdmi00200101() {
        return new Admi00200101();
    }

    /**
     * Create an instance of {@link InstructionTypeStatus1Choice }
     * 
     */
    public InstructionTypeStatus1Choice createInstructionTypeStatus1Choice() {
        return new InstructionTypeStatus1Choice();
    }

    /**
     * Create an instance of {@link CapitalGainFormat1Choice }
     * 
     */
    public CapitalGainFormat1Choice createCapitalGainFormat1Choice() {
        return new CapitalGainFormat1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     * 
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link VoteInstructionForMeetingResolution1Choice }
     * 
     */
    public VoteInstructionForMeetingResolution1Choice createVoteInstructionForMeetingResolution1Choice() {
        return new VoteInstructionForMeetingResolution1Choice();
    }

    /**
     * Create an instance of {@link Meeting3 }
     * 
     */
    public Meeting3 createMeeting3() {
        return new Meeting3();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAnd13DecimalAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAnd13DecimalAmount createActiveOrHistoricCurrencyAnd13DecimalAmount() {
        return new ActiveOrHistoricCurrencyAnd13DecimalAmount();
    }

    /**
     * Create an instance of {@link XtnsnPartyIdentification200 }
     * 
     */
    public XtnsnPartyIdentification200 createXtnsnPartyIdentification200() {
        return new XtnsnPartyIdentification200();
    }

    /**
     * Create an instance of {@link CorporateEventNarrative2 }
     * 
     */
    public CorporateEventNarrative2 createCorporateEventNarrative2() {
        return new CorporateEventNarrative2();
    }

    /**
     * Create an instance of {@link CorporateActionDate15 }
     * 
     */
    public CorporateActionDate15 createCorporateActionDate15() {
        return new CorporateActionDate15();
    }

    /**
     * Create an instance of {@link TemporaryFinancialInstrumentIndicator1Choice }
     * 
     */
    public TemporaryFinancialInstrumentIndicator1Choice createTemporaryFinancialInstrumentIndicator1Choice() {
        return new TemporaryFinancialInstrumentIndicator1Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link IdentificationSource3Choice }
     * 
     */
    public IdentificationSource3Choice createIdentificationSource3Choice() {
        return new IdentificationSource3Choice();
    }

    /**
     * Create an instance of {@link XtnsnMtngAthrty }
     * 
     */
    public XtnsnMtngAthrty createXtnsnMtngAthrty() {
        return new XtnsnMtngAthrty();
    }

    /**
     * Create an instance of {@link CorporateActionEventReference1 }
     * 
     */
    public CorporateActionEventReference1 createCorporateActionEventReference1() {
        return new CorporateActionEventReference1();
    }

    /**
     * Create an instance of {@link IssuerInformation1 }
     * 
     */
    public IssuerInformation1 createIssuerInformation1() {
        return new IssuerInformation1();
    }

    /**
     * Create an instance of {@link CorporateActionDate23 }
     * 
     */
    public CorporateActionDate23 createCorporateActionDate23() {
        return new CorporateActionDate23();
    }

    /**
     * Create an instance of {@link UpdatedURLlnformation }
     * 
     */
    public UpdatedURLlnformation createUpdatedURLlnformation() {
        return new UpdatedURLlnformation();
    }

    /**
     * Create an instance of {@link RateType20Choice }
     * 
     */
    public RateType20Choice createRateType20Choice() {
        return new RateType20Choice();
    }

    /**
     * Create an instance of {@link CorporateActionDate27 }
     * 
     */
    public CorporateActionDate27 createCorporateActionDate27() {
        return new CorporateActionDate27();
    }

    /**
     * Create an instance of {@link DocumentMeetingInstructionStatus }
     * 
     */
    public DocumentMeetingInstructionStatus createDocumentMeetingInstructionStatus() {
        return new DocumentMeetingInstructionStatus();
    }

    /**
     * Create an instance of {@link CorporateActionQuantity5 }
     * 
     */
    public CorporateActionQuantity5 createCorporateActionQuantity5() {
        return new CorporateActionQuantity5();
    }

    /**
     * Create an instance of {@link CommunicationAddress4 }
     * 
     */
    public CommunicationAddress4 createCommunicationAddress4() {
        return new CommunicationAddress4();
    }

    /**
     * Create an instance of {@link BeneficiaryCertificationType5Choice }
     * 
     */
    public BeneficiaryCertificationType5Choice createBeneficiaryCertificationType5Choice() {
        return new BeneficiaryCertificationType5Choice();
    }

    /**
     * Create an instance of {@link RateTypeAndAmountAndStatus11 }
     * 
     */
    public RateTypeAndAmountAndStatus11 createRateTypeAndAmountAndStatus11() {
        return new RateTypeAndAmountAndStatus11();
    }

    /**
     * Create an instance of {@link OptionFeaturesFormat9Choice }
     * 
     */
    public OptionFeaturesFormat9Choice createOptionFeaturesFormat9Choice() {
        return new OptionFeaturesFormat9Choice();
    }

    /**
     * Create an instance of {@link RateTypeAndAmountAndStatus14 }
     * 
     */
    public RateTypeAndAmountAndStatus14 createRateTypeAndAmountAndStatus14() {
        return new RateTypeAndAmountAndStatus14();
    }

    /**
     * Create an instance of {@link RateTypeAndAmountAndStatus13 }
     * 
     */
    public RateTypeAndAmountAndStatus13 createRateTypeAndAmountAndStatus13() {
        return new RateTypeAndAmountAndStatus13();
    }

    /**
     * Create an instance of {@link LotteryTypeFormat1Choice }
     * 
     */
    public LotteryTypeFormat1Choice createLotteryTypeFormat1Choice() {
        return new LotteryTypeFormat1Choice();
    }

    /**
     * Create an instance of {@link RateTypeAndAmountAndStatus16 }
     * 
     */
    public RateTypeAndAmountAndStatus16 createRateTypeAndAmountAndStatus16() {
        return new RateTypeAndAmountAndStatus16();
    }

    /**
     * Create an instance of {@link RateTypeAndAmountAndStatus15 }
     * 
     */
    public RateTypeAndAmountAndStatus15 createRateTypeAndAmountAndStatus15() {
        return new RateTypeAndAmountAndStatus15();
    }

    /**
     * Create an instance of {@link CashOption24 }
     * 
     */
    public CashOption24 createCashOption24() {
        return new CashOption24();
    }

    /**
     * Create an instance of {@link SubAccount2 }
     * 
     */
    public SubAccount2 createSubAccount2() {
        return new SubAccount2();
    }

    /**
     * Create an instance of {@link LocationFormat1Choice }
     * 
     */
    public LocationFormat1Choice createLocationFormat1Choice() {
        return new LocationFormat1Choice();
    }

    /**
     * Create an instance of {@link ClassificationType2Choice }
     * 
     */
    public ClassificationType2Choice createClassificationType2Choice() {
        return new ClassificationType2Choice();
    }

    /**
     * Create an instance of {@link DetailedInstructionStatus8 }
     * 
     */
    public DetailedInstructionStatus8 createDetailedInstructionStatus8() {
        return new DetailedInstructionStatus8();
    }

    /**
     * Create an instance of {@link UnitOrFaceAmountOrCode1Choice }
     * 
     */
    public UnitOrFaceAmountOrCode1Choice createUnitOrFaceAmountOrCode1Choice() {
        return new UnitOrFaceAmountOrCode1Choice();
    }

    /**
     * Create an instance of {@link IndicativeOrMarketPrice5Choice }
     * 
     */
    public IndicativeOrMarketPrice5Choice createIndicativeOrMarketPrice5Choice() {
        return new IndicativeOrMarketPrice5Choice();
    }

    /**
     * Create an instance of {@link AlternateIdentification1 }
     * 
     */
    public AlternateIdentification1 createAlternateIdentification1() {
        return new AlternateIdentification1();
    }

    /**
     * Create an instance of {@link PartyIdentification9Choice }
     * 
     */
    public PartyIdentification9Choice createPartyIdentification9Choice() {
        return new PartyIdentification9Choice();
    }

    /**
     * Create an instance of {@link IdentificationSource1Choice }
     * 
     */
    public IdentificationSource1Choice createIdentificationSource1Choice() {
        return new IdentificationSource1Choice();
    }

    /**
     * Create an instance of {@link RateType11Choice }
     * 
     */
    public RateType11Choice createRateType11Choice() {
        return new RateType11Choice();
    }

    /**
     * Create an instance of {@link DistributionTypeFormat3Choice }
     * 
     */
    public DistributionTypeFormat3Choice createDistributionTypeFormat3Choice() {
        return new DistributionTypeFormat3Choice();
    }

    /**
     * Create an instance of {@link Period4 }
     * 
     */
    public Period4 createPeriod4() {
        return new Period4();
    }

    /**
     * Create an instance of {@link InstructionStatus4Choice }
     * 
     */
    public InstructionStatus4Choice createInstructionStatus4Choice() {
        return new InstructionStatus4Choice();
    }

    /**
     * Create an instance of {@link MeetingInstructionV04 }
     * 
     */
    public MeetingInstructionV04 createMeetingInstructionV04() {
        return new MeetingInstructionV04();
    }

    /**
     * Create an instance of {@link SafekeepingPlaceAsCodeAndPartyIdentification }
     * 
     */
    public SafekeepingPlaceAsCodeAndPartyIdentification createSafekeepingPlaceAsCodeAndPartyIdentification() {
        return new SafekeepingPlaceAsCodeAndPartyIdentification();
    }

    /**
     * Create an instance of {@link PartyIdentification3 }
     * 
     */
    public PartyIdentification3 createPartyIdentification3() {
        return new PartyIdentification3();
    }

    /**
     * Create an instance of {@link IndividualPerson17 }
     * 
     */
    public IndividualPerson17 createIndividualPerson17() {
        return new IndividualPerson17();
    }

    /**
     * Create an instance of {@link RateType22Choice }
     * 
     */
    public RateType22Choice createRateType22Choice() {
        return new RateType22Choice();
    }

    /**
     * Create an instance of {@link IndividualPerson16 }
     * 
     */
    public IndividualPerson16 createIndividualPerson16() {
        return new IndividualPerson16();
    }

    /**
     * Create an instance of {@link VoteDetails2 }
     * 
     */
    public VoteDetails2 createVoteDetails2() {
        return new VoteDetails2();
    }

    /**
     * Create an instance of {@link Proxy1Choice }
     * 
     */
    public Proxy1Choice createProxy1Choice() {
        return new Proxy1Choice();
    }

    /**
     * Create an instance of {@link SpecificInstructionRequest1 }
     * 
     */
    public SpecificInstructionRequest1 createSpecificInstructionRequest1() {
        return new SpecificInstructionRequest1();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link OriginalAndCurrentQuantities1 }
     * 
     */
    public OriginalAndCurrentQuantities1 createOriginalAndCurrentQuantities1() {
        return new OriginalAndCurrentQuantities1();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     * 
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link PersonIdentification6 }
     * 
     */
    public PersonIdentification6 createPersonIdentification6() {
        return new PersonIdentification6();
    }

    /**
     * Create an instance of {@link MessageIdentification1 }
     * 
     */
    public MessageIdentification1 createMessageIdentification1() {
        return new MessageIdentification1();
    }

    /**
     * Create an instance of {@link CancellationRejectionStatus1Choice }
     * 
     */
    public CancellationRejectionStatus1Choice createCancellationRejectionStatus1Choice() {
        return new CancellationRejectionStatus1Choice();
    }

    /**
     * Create an instance of {@link ConversionTypeFormat1Choice }
     * 
     */
    public ConversionTypeFormat1Choice createConversionTypeFormat1Choice() {
        return new ConversionTypeFormat1Choice();
    }

    /**
     * Create an instance of {@link AdditionalBusinessProcessFormat1Choice }
     * 
     */
    public AdditionalBusinessProcessFormat1Choice createAdditionalBusinessProcessFormat1Choice() {
        return new AdditionalBusinessProcessFormat1Choice();
    }

    /**
     * Create an instance of {@link ProxyAppointmentInformation2 }
     * 
     */
    public ProxyAppointmentInformation2 createProxyAppointmentInformation2() {
        return new ProxyAppointmentInformation2();
    }

    /**
     * Create an instance of {@link ElectionTypeFormat1Choice }
     * 
     */
    public ElectionTypeFormat1Choice createElectionTypeFormat1Choice() {
        return new ElectionTypeFormat1Choice();
    }

    /**
     * Create an instance of {@link RateType23Choice }
     * 
     */
    public RateType23Choice createRateType23Choice() {
        return new RateType23Choice();
    }

    /**
     * Create an instance of {@link OfferTypeFormat3Choice }
     * 
     */
    public OfferTypeFormat3Choice createOfferTypeFormat3Choice() {
        return new OfferTypeFormat3Choice();
    }

    /**
     * Create an instance of {@link GrossDividendRateFormat9Choice }
     * 
     */
    public GrossDividendRateFormat9Choice createGrossDividendRateFormat9Choice() {
        return new GrossDividendRateFormat9Choice();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link PostalAddress1 }
     * 
     */
    public PostalAddress1 createPostalAddress1() {
        return new PostalAddress1();
    }

    /**
     * Create an instance of {@link InstructionType1Choice }
     * 
     */
    public InstructionType1Choice createInstructionType1Choice() {
        return new InstructionType1Choice();
    }

    /**
     * Create an instance of {@link ContactDetails2 }
     * 
     */
    public ContactDetails2 createContactDetails2() {
        return new ContactDetails2();
    }

    /**
     * Create an instance of {@link InstructionRejectionStatus1Choice }
     * 
     */
    public InstructionRejectionStatus1Choice createInstructionRejectionStatus1Choice() {
        return new InstructionRejectionStatus1Choice();
    }

    /**
     * Create an instance of {@link PowerOfAttorneyRequirements2 }
     * 
     */
    public PowerOfAttorneyRequirements2 createPowerOfAttorneyRequirements2() {
        return new PowerOfAttorneyRequirements2();
    }

    /**
     * Create an instance of {@link DateFormat19Choice }
     * 
     */
    public DateFormat19Choice createDateFormat19Choice() {
        return new DateFormat19Choice();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link MeetingCancellationReason1Choice }
     * 
     */
    public MeetingCancellationReason1Choice createMeetingCancellationReason1Choice() {
        return new MeetingCancellationReason1Choice();
    }

    /**
     * Create an instance of {@link CorporateActionAmounts21 }
     * 
     */
    public CorporateActionAmounts21 createCorporateActionAmounts21() {
        return new CorporateActionAmounts21();
    }

    /**
     * Create an instance of {@link DocumentMeetingInstruction }
     * 
     */
    public DocumentMeetingInstruction createDocumentMeetingInstruction() {
        return new DocumentMeetingInstruction();
    }

    /**
     * Create an instance of {@link CorporateAction10 }
     * 
     */
    public CorporateAction10 createCorporateAction10() {
        return new CorporateAction10();
    }

    /**
     * Create an instance of {@link ExtensionEnvelope1 }
     * 
     */
    public ExtensionEnvelope1 createExtensionEnvelope1() {
        return new ExtensionEnvelope1();
    }

    /**
     * Create an instance of {@link AdditionalRightThreshold1Choice }
     * 
     */
    public AdditionalRightThreshold1Choice createAdditionalRightThreshold1Choice() {
        return new AdditionalRightThreshold1Choice();
    }

    /**
     * Create an instance of {@link MeetingResultDisseminationV04 }
     * 
     */
    public MeetingResultDisseminationV04 createMeetingResultDisseminationV04() {
        return new MeetingResultDisseminationV04();
    }

    /**
     * Create an instance of {@link CorporateActionPeriod8 }
     * 
     */
    public CorporateActionPeriod8 createCorporateActionPeriod8() {
        return new CorporateActionPeriod8();
    }

    /**
     * Create an instance of {@link RateType17Choice }
     * 
     */
    public RateType17Choice createRateType17Choice() {
        return new RateType17Choice();
    }

    /**
     * Create an instance of {@link CorporateActionPeriod7 }
     * 
     */
    public CorporateActionPeriod7 createCorporateActionPeriod7() {
        return new CorporateActionPeriod7();
    }

    /**
     * Create an instance of {@link DocumentMtngNtfctn }
     * 
     */
    public DocumentMtngNtfctn createDocumentMtngNtfctn() {
        return new DocumentMtngNtfctn();
    }

    /**
     * Create an instance of {@link PartyIdentification42 }
     * 
     */
    public PartyIdentification42 createPartyIdentification42() {
        return new PartyIdentification42();
    }

    /**
     * Create an instance of {@link GenericIdentification13 }
     * 
     */
    public GenericIdentification13 createGenericIdentification13() {
        return new GenericIdentification13();
    }

    /**
     * Create an instance of {@link DefaultProcessingOrStandingInstruction1Choice }
     * 
     */
    public DefaultProcessingOrStandingInstruction1Choice createDefaultProcessingOrStandingInstruction1Choice() {
        return new DefaultProcessingOrStandingInstruction1Choice();
    }

    /**
     * Create an instance of {@link GenericIdentification19 }
     * 
     */
    public GenericIdentification19 createGenericIdentification19() {
        return new GenericIdentification19();
    }

    /**
     * Create an instance of {@link CorporateActionRate28 }
     * 
     */
    public CorporateActionRate28 createCorporateActionRate28() {
        return new CorporateActionRate28();
    }

    /**
     * Create an instance of {@link RateFormat3Choice }
     * 
     */
    public RateFormat3Choice createRateFormat3Choice() {
        return new RateFormat3Choice();
    }

    /**
     * Create an instance of {@link GenericIdentification20 }
     * 
     */
    public GenericIdentification20 createGenericIdentification20() {
        return new GenericIdentification20();
    }

    /**
     * Create an instance of {@link NetDividendRateFormat11Choice }
     * 
     */
    public NetDividendRateFormat11Choice createNetDividendRateFormat11Choice() {
        return new NetDividendRateFormat11Choice();
    }

    /**
     * Create an instance of {@link NameAndAddress9 }
     * 
     */
    public NameAndAddress9 createNameAndAddress9() {
        return new NameAndAddress9();
    }

    /**
     * Create an instance of {@link QuorumQuantity1Choice }
     * 
     */
    public QuorumQuantity1Choice createQuorumQuantity1Choice() {
        return new QuorumQuantity1Choice();
    }

    /**
     * Create an instance of {@link MessageIdentification }
     * 
     */
    public MessageIdentification createMessageIdentification() {
        return new MessageIdentification();
    }

    /**
     * Create an instance of {@link NameAndAddress5 }
     * 
     */
    public NameAndAddress5 createNameAndAddress5() {
        return new NameAndAddress5();
    }

    /**
     * Create an instance of {@link SolicitationFeeRateFormat5Choice }
     * 
     */
    public SolicitationFeeRateFormat5Choice createSolicitationFeeRateFormat5Choice() {
        return new SolicitationFeeRateFormat5Choice();
    }

    /**
     * Create an instance of {@link CorporateActionRate35 }
     * 
     */
    public CorporateActionRate35 createCorporateActionRate35() {
        return new CorporateActionRate35();
    }

    /**
     * Create an instance of {@link AmountToAmountRatio2 }
     * 
     */
    public AmountToAmountRatio2 createAmountToAmountRatio2() {
        return new AmountToAmountRatio2();
    }

    /**
     * Create an instance of {@link CorporateActionRate36 }
     * 
     */
    public CorporateActionRate36 createCorporateActionRate36() {
        return new CorporateActionRate36();
    }

    /**
     * Create an instance of {@link OrganisationIdentification7 }
     * 
     */
    public OrganisationIdentification7 createOrganisationIdentification7() {
        return new OrganisationIdentification7();
    }

    /**
     * Create an instance of {@link FinancialInstrumentQuantity20Choice }
     * 
     */
    public FinancialInstrumentQuantity20Choice createFinancialInstrumentQuantity20Choice() {
        return new FinancialInstrumentQuantity20Choice();
    }

    /**
     * Create an instance of {@link UpdatedAdditionalInformation1 }
     * 
     */
    public UpdatedAdditionalInformation1 createUpdatedAdditionalInformation1() {
        return new UpdatedAdditionalInformation1();
    }

    /**
     * Create an instance of {@link Event1 }
     * 
     */
    public Event1 createEvent1() {
        return new Event1();
    }

    /**
     * Create an instance of {@link UpdatedAdditionalInformation3 }
     * 
     */
    public UpdatedAdditionalInformation3 createUpdatedAdditionalInformation3() {
        return new UpdatedAdditionalInformation3();
    }

    /**
     * Create an instance of {@link UpdatedAdditionalInformation2 }
     * 
     */
    public UpdatedAdditionalInformation2 createUpdatedAdditionalInformation2() {
        return new UpdatedAdditionalInformation2();
    }

    /**
     * Create an instance of {@link InterestComputationMethodFormat1Choice }
     * 
     */
    public InterestComputationMethodFormat1Choice createInterestComputationMethodFormat1Choice() {
        return new InterestComputationMethodFormat1Choice();
    }

    /**
     * Create an instance of {@link IncentivePremiumType1Choice }
     * 
     */
    public IncentivePremiumType1Choice createIncentivePremiumType1Choice() {
        return new IncentivePremiumType1Choice();
    }

    /**
     * Create an instance of {@link QuantityToQuantityRatio1 }
     * 
     */
    public QuantityToQuantityRatio1 createQuantityToQuantityRatio1() {
        return new QuantityToQuantityRatio1();
    }

    /**
     * Create an instance of {@link BusinessApplicationHeaderV01 }
     * 
     */
    public BusinessApplicationHeaderV01 createBusinessApplicationHeaderV01() {
        return new BusinessApplicationHeaderV01();
    }

    /**
     * Create an instance of {@link GrossDividendRateFormat7Choice }
     * 
     */
    public GrossDividendRateFormat7Choice createGrossDividendRateFormat7Choice() {
        return new GrossDividendRateFormat7Choice();
    }

    /**
     * Create an instance of {@link RenounceableEntitlementStatusTypeFormat1Choice }
     * 
     */
    public RenounceableEntitlementStatusTypeFormat1Choice createRenounceableEntitlementStatusTypeFormat1Choice() {
        return new RenounceableEntitlementStatusTypeFormat1Choice();
    }

    /**
     * Create an instance of {@link SecurityIdentification11Choice }
     * 
     */
    public SecurityIdentification11Choice createSecurityIdentification11Choice() {
        return new SecurityIdentification11Choice();
    }

    /**
     * Create an instance of {@link CorporateActionOption10Choice }
     * 
     */
    public CorporateActionOption10Choice createCorporateActionOption10Choice() {
        return new CorporateActionOption10Choice();
    }

    /**
     * Create an instance of {@link PercentagePrice1 }
     * 
     */
    public PercentagePrice1 createPercentagePrice1() {
        return new PercentagePrice1();
    }

    /**
     * Create an instance of {@link AmountPrice3 }
     * 
     */
    public AmountPrice3 createAmountPrice3() {
        return new AmountPrice3();
    }

    /**
     * Create an instance of {@link AmountPrice2 }
     * 
     */
    public AmountPrice2 createAmountPrice2() {
        return new AmountPrice2();
    }

    /**
     * Create an instance of {@link FractionDispositionType19Choice }
     * 
     */
    public FractionDispositionType19Choice createFractionDispositionType19Choice() {
        return new FractionDispositionType19Choice();
    }

    /**
     * Create an instance of {@link Extension2 }
     * 
     */
    public Extension2 createExtension2() {
        return new Extension2();
    }

    /**
     * Create an instance of {@link Admi00400101 }
     * 
     */
    public Admi00400101 createAdmi00400101() {
        return new Admi00400101();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link RateAndAmountFormat14Choice }
     * 
     */
    public RateAndAmountFormat14Choice createRateAndAmountFormat14Choice() {
        return new RateAndAmountFormat14Choice();
    }

    /**
     * Create an instance of {@link DateCode3Choice }
     * 
     */
    public DateCode3Choice createDateCode3Choice() {
        return new DateCode3Choice();
    }

    /**
     * Create an instance of {@link RateFormat6Choice }
     * 
     */
    public RateFormat6Choice createRateFormat6Choice() {
        return new RateFormat6Choice();
    }

    /**
     * Create an instance of {@link VoteParameters3 }
     * 
     */
    public VoteParameters3 createVoteParameters3() {
        return new VoteParameters3();
    }

    /**
     * Create an instance of {@link SafekeepingAccount4 }
     * 
     */
    public SafekeepingAccount4 createSafekeepingAccount4() {
        return new SafekeepingAccount4();
    }

    /**
     * Create an instance of {@link DateCodeAndTimeFormat1 }
     * 
     */
    public DateCodeAndTimeFormat1 createDateCodeAndTimeFormat1() {
        return new DateCodeAndTimeFormat1();
    }

    /**
     * Create an instance of {@link Party9Choice }
     * 
     */
    public Party9Choice createParty9Choice() {
        return new Party9Choice();
    }

    /**
     * Create an instance of {@link IdentificationFormat1Choice }
     * 
     */
    public IdentificationFormat1Choice createIdentificationFormat1Choice() {
        return new IdentificationFormat1Choice();
    }

    /**
     * Create an instance of {@link SecuritiesOption23 }
     * 
     */
    public SecuritiesOption23 createSecuritiesOption23() {
        return new SecuritiesOption23();
    }

    /**
     * Create an instance of {@link DocumentMtgCxl }
     * 
     */
    public DocumentMtgCxl createDocumentMtgCxl() {
        return new DocumentMtgCxl();
    }

    /**
     * Create an instance of {@link CorporateActionPrice28 }
     * 
     */
    public CorporateActionPrice28 createCorporateActionPrice28() {
        return new CorporateActionPrice28();
    }

    /**
     * Create an instance of {@link CertificationTypeFormat1Choice }
     * 
     */
    public CertificationTypeFormat1Choice createCertificationTypeFormat1Choice() {
        return new CertificationTypeFormat1Choice();
    }

    /**
     * Create an instance of {@link RateType21Choice }
     * 
     */
    public RateType21Choice createRateType21Choice() {
        return new RateType21Choice();
    }

    /**
     * Create an instance of {@link IncentivePremium3 }
     * 
     */
    public IncentivePremium3 createIncentivePremium3() {
        return new IncentivePremium3();
    }

    /**
     * Create an instance of {@link PriceDetails10 }
     * 
     */
    public PriceDetails10 createPriceDetails10() {
        return new PriceDetails10();
    }

    /**
     * Create an instance of {@link AmountPricePerAmount2 }
     * 
     */
    public AmountPricePerAmount2 createAmountPricePerAmount2() {
        return new AmountPricePerAmount2();
    }

    /**
     * Create an instance of {@link SecuritiesOption33 }
     * 
     */
    public SecuritiesOption33 createSecuritiesOption33() {
        return new SecuritiesOption33();
    }

    /**
     * Create an instance of {@link CorporateActionPrice17 }
     * 
     */
    public CorporateActionPrice17 createCorporateActionPrice17() {
        return new CorporateActionPrice17();
    }

    /**
     * Create an instance of {@link RateFormat8Choice }
     * 
     */
    public RateFormat8Choice createRateFormat8Choice() {
        return new RateFormat8Choice();
    }

    /**
     * Create an instance of {@link PriceFormat23Choice }
     * 
     */
    public PriceFormat23Choice createPriceFormat23Choice() {
        return new PriceFormat23Choice();
    }

    /**
     * Create an instance of {@link OtherIdentification1 }
     * 
     */
    public OtherIdentification1 createOtherIdentification1() {
        return new OtherIdentification1();
    }

    /**
     * Create an instance of {@link PersonIdentificationType1Choice }
     * 
     */
    public PersonIdentificationType1Choice createPersonIdentificationType1Choice() {
        return new PersonIdentificationType1Choice();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link RejectionReason2 }
     * 
     */
    public RejectionReason2 createRejectionReason2() {
        return new RejectionReason2();
    }

    /**
     * Create an instance of {@link SecurityDate9 }
     * 
     */
    public SecurityDate9 createSecurityDate9() {
        return new SecurityDate9();
    }

    /**
     * Create an instance of {@link DateFormat11Choice }
     * 
     */
    public DateFormat11Choice createDateFormat11Choice() {
        return new DateFormat11Choice();
    }

    /**
     * Create an instance of {@link XtnsnMeetingNotification.XtnsnDt }
     * 
     */
    public XtnsnMeetingNotification.XtnsnDt createXtnsnMeetingNotificationXtnsnDt() {
        return new XtnsnMeetingNotification.XtnsnDt();
    }

    /**
     * Create an instance of {@link XtnsnMeetingResultDissemination.XtnsnDt }
     * 
     */
    public XtnsnMeetingResultDissemination.XtnsnDt createXtnsnMeetingResultDisseminationXtnsnDt() {
        return new XtnsnMeetingResultDissemination.XtnsnDt();
    }

    /**
     * Create an instance of {@link XtnsnMeetingCancellation.XtnsnDt }
     * 
     */
    public XtnsnMeetingCancellation.XtnsnDt createXtnsnMeetingCancellationXtnsnDt() {
        return new XtnsnMeetingCancellation.XtnsnDt();
    }

    /**
     * Create an instance of {@link XtnsnMeetingInstruction.XtnsnDt }
     * 
     */
    public XtnsnMeetingInstruction.XtnsnDt createXtnsnMeetingInstructionXtnsnDt() {
        return new XtnsnMeetingInstruction.XtnsnDt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeetingInstructionStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MeetingInstructionStatus")
    public JAXBElement<MeetingInstructionStatus> createMeetingInstructionStatus(MeetingInstructionStatus value) {
        return new JAXBElement<MeetingInstructionStatus>(_MeetingInstructionStatus_QNAME, MeetingInstructionStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeetingNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MeetingNotification")
    public JAXBElement<MeetingNotification> createMeetingNotification(MeetingNotification value) {
        return new JAXBElement<MeetingNotification>(_MeetingNotification_QNAME, MeetingNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeetingResultDissemination }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MeetingResultDissemination")
    public JAXBElement<MeetingResultDissemination> createMeetingResultDissemination(MeetingResultDissemination value) {
        return new JAXBElement<MeetingResultDissemination>(_MeetingResultDissemination_QNAME, MeetingResultDissemination.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageReject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageReject")
    public JAXBElement<MessageReject> createMessageReject(MessageReject value) {
        return new JAXBElement<MessageReject>(_MessageReject_QNAME, MessageReject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemEventNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SystemEventNotification")
    public JAXBElement<SystemEventNotification> createSystemEventNotification(SystemEventNotification value) {
        return new JAXBElement<SystemEventNotification>(_SystemEventNotification_QNAME, SystemEventNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeetingInstruction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MeetingInstruction")
    public JAXBElement<MeetingInstruction> createMeetingInstruction(MeetingInstruction value) {
        return new JAXBElement<MeetingInstruction>(_MeetingInstruction_QNAME, MeetingInstruction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeetingCancellation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MeetingCancellation")
    public JAXBElement<MeetingCancellation> createMeetingCancellation(MeetingCancellation value) {
        return new JAXBElement<MeetingCancellation>(_MeetingCancellation_QNAME, MeetingCancellation.class, null, value);
    }

}
