//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.iso20022.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecuritiesEntryType2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecuritiesEntryType2Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BLOK"/>
 *     &lt;enumeration value="ELIG"/>
 *     &lt;enumeration value="PEND"/>
 *     &lt;enumeration value="PENR"/>
 *     &lt;enumeration value="NOMI"/>
 *     &lt;enumeration value="SETD"/>
 *     &lt;enumeration value="BORR"/>
 *     &lt;enumeration value="LOAN"/>
 *     &lt;enumeration value="SPOS"/>
 *     &lt;enumeration value="TRAD"/>
 *     &lt;enumeration value="COLI"/>
 *     &lt;enumeration value="COLO"/>
 *     &lt;enumeration value="UNBA"/>
 *     &lt;enumeration value="INBA"/>
 *     &lt;enumeration value="REGO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SecuritiesEntryType2Code")
@XmlEnum
public enum SecuritiesEntryType2Code {

    BLOK,
    ELIG,
    PEND,
    PENR,
    NOMI,
    SETD,
    BORR,
    LOAN,
    SPOS,
    TRAD,
    COLI,
    COLO,
    UNBA,
    INBA,
    REGO;

    public String value() {
        return name();
    }

    public static SecuritiesEntryType2Code fromValue(String v) {
        return valueOf(v);
    }

}
