//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.datamodel.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorporateActionDate27 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CorporateActionDate27">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AnncmntDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="CertfctnDdln" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="CrtApprvlDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="EarlyClsgDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="FctvDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="EqulstnDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="FrthrDtldAnncmntDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="FxgDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="LtryDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="NewMtrtyDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="MtgDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="MrgnFxgDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="PrratnDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="RcrdDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="RegnDdln" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="RsltsPblctnDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="DdlnToSplt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="DdlnForTaxBrkdwnInstr" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="TradgSspdDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="UcondlDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="WhlyUcondlDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="ExDvddDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="OffclAnncmntPblctnDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="SpclExDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="GrntedPrtcptnDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="ElctnToCtrPtyDdln" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="LpsdDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="PmtDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="ThrdPtyDdln" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="EarlyThrdPtyDdln" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="MktClmTrckgEndDt" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="LeadPlntffDdln" type="{}DateFormat19Choice" minOccurs="0"/>
 *         &lt;element name="FilgDt" type="{}DateFormat16Choice" minOccurs="0"/>
 *         &lt;element name="HrgDt" type="{}DateFormat16Choice" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorporateActionDate27", propOrder = {
    "anncmntDt",
    "certfctnDdln",
    "crtApprvlDt",
    "earlyClsgDt",
    "fctvDt",
    "equlstnDt",
    "frthrDtldAnncmntDt",
    "fxgDt",
    "ltryDt",
    "newMtrtyDt",
    "mtgDt",
    "mrgnFxgDt",
    "prratnDt",
    "rcrdDt",
    "regnDdln",
    "rsltsPblctnDt",
    "ddlnToSplt",
    "ddlnForTaxBrkdwnInstr",
    "tradgSspdDt",
    "ucondlDt",
    "whlyUcondlDt",
    "exDvddDt",
    "offclAnncmntPblctnDt",
    "spclExDt",
    "grntedPrtcptnDt",
    "elctnToCtrPtyDdln",
    "lpsdDt",
    "pmtDt",
    "thrdPtyDdln",
    "earlyThrdPtyDdln",
    "mktClmTrckgEndDt",
    "leadPlntffDdln",
    "filgDt",
    "hrgDt"
})
public class CorporateActionDate27 {

    @XmlElement(name = "AnncmntDt")
    protected DateFormat19Choice anncmntDt;
    @XmlElement(name = "CertfctnDdln")
    protected DateFormat19Choice certfctnDdln;
    @XmlElement(name = "CrtApprvlDt")
    protected DateFormat19Choice crtApprvlDt;
    @XmlElement(name = "EarlyClsgDt")
    protected DateFormat19Choice earlyClsgDt;
    @XmlElement(name = "FctvDt")
    protected DateFormat19Choice fctvDt;
    @XmlElement(name = "EqulstnDt")
    protected DateFormat19Choice equlstnDt;
    @XmlElement(name = "FrthrDtldAnncmntDt")
    protected DateFormat19Choice frthrDtldAnncmntDt;
    @XmlElement(name = "FxgDt")
    protected DateFormat19Choice fxgDt;
    @XmlElement(name = "LtryDt")
    protected DateFormat19Choice ltryDt;
    @XmlElement(name = "NewMtrtyDt")
    protected DateFormat19Choice newMtrtyDt;
    @XmlElement(name = "MtgDt")
    protected DateFormat19Choice mtgDt;
    @XmlElement(name = "MrgnFxgDt")
    protected DateFormat19Choice mrgnFxgDt;
    @XmlElement(name = "PrratnDt")
    protected DateFormat19Choice prratnDt;
    @XmlElement(name = "RcrdDt")
    protected DateFormat19Choice rcrdDt;
    @XmlElement(name = "RegnDdln")
    protected DateFormat19Choice regnDdln;
    @XmlElement(name = "RsltsPblctnDt")
    protected DateFormat19Choice rsltsPblctnDt;
    @XmlElement(name = "DdlnToSplt")
    protected DateFormat19Choice ddlnToSplt;
    @XmlElement(name = "DdlnForTaxBrkdwnInstr")
    protected DateFormat19Choice ddlnForTaxBrkdwnInstr;
    @XmlElement(name = "TradgSspdDt")
    protected DateFormat19Choice tradgSspdDt;
    @XmlElement(name = "UcondlDt")
    protected DateFormat19Choice ucondlDt;
    @XmlElement(name = "WhlyUcondlDt")
    protected DateFormat19Choice whlyUcondlDt;
    @XmlElement(name = "ExDvddDt")
    protected DateFormat19Choice exDvddDt;
    @XmlElement(name = "OffclAnncmntPblctnDt")
    protected DateFormat19Choice offclAnncmntPblctnDt;
    @XmlElement(name = "SpclExDt")
    protected DateFormat19Choice spclExDt;
    @XmlElement(name = "GrntedPrtcptnDt")
    protected DateFormat19Choice grntedPrtcptnDt;
    @XmlElement(name = "ElctnToCtrPtyDdln")
    protected DateFormat19Choice elctnToCtrPtyDdln;
    @XmlElement(name = "LpsdDt")
    protected DateFormat19Choice lpsdDt;
    @XmlElement(name = "PmtDt")
    protected DateFormat19Choice pmtDt;
    @XmlElement(name = "ThrdPtyDdln")
    protected DateFormat19Choice thrdPtyDdln;
    @XmlElement(name = "EarlyThrdPtyDdln")
    protected DateFormat19Choice earlyThrdPtyDdln;
    @XmlElement(name = "MktClmTrckgEndDt")
    protected DateFormat19Choice mktClmTrckgEndDt;
    @XmlElement(name = "LeadPlntffDdln")
    protected DateFormat19Choice leadPlntffDdln;
    @XmlElement(name = "FilgDt")
    protected DateFormat16Choice filgDt;
    @XmlElement(name = "HrgDt")
    protected DateFormat16Choice hrgDt;

    /**
     * Gets the value of the anncmntDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getAnncmntDt() {
        return anncmntDt;
    }

    /**
     * Sets the value of the anncmntDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setAnncmntDt(DateFormat19Choice value) {
        this.anncmntDt = value;
    }

    /**
     * Gets the value of the certfctnDdln property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getCertfctnDdln() {
        return certfctnDdln;
    }

    /**
     * Sets the value of the certfctnDdln property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setCertfctnDdln(DateFormat19Choice value) {
        this.certfctnDdln = value;
    }

    /**
     * Gets the value of the crtApprvlDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getCrtApprvlDt() {
        return crtApprvlDt;
    }

    /**
     * Sets the value of the crtApprvlDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setCrtApprvlDt(DateFormat19Choice value) {
        this.crtApprvlDt = value;
    }

    /**
     * Gets the value of the earlyClsgDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getEarlyClsgDt() {
        return earlyClsgDt;
    }

    /**
     * Sets the value of the earlyClsgDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setEarlyClsgDt(DateFormat19Choice value) {
        this.earlyClsgDt = value;
    }

    /**
     * Gets the value of the fctvDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getFctvDt() {
        return fctvDt;
    }

    /**
     * Sets the value of the fctvDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setFctvDt(DateFormat19Choice value) {
        this.fctvDt = value;
    }

    /**
     * Gets the value of the equlstnDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getEqulstnDt() {
        return equlstnDt;
    }

    /**
     * Sets the value of the equlstnDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setEqulstnDt(DateFormat19Choice value) {
        this.equlstnDt = value;
    }

    /**
     * Gets the value of the frthrDtldAnncmntDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getFrthrDtldAnncmntDt() {
        return frthrDtldAnncmntDt;
    }

    /**
     * Sets the value of the frthrDtldAnncmntDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setFrthrDtldAnncmntDt(DateFormat19Choice value) {
        this.frthrDtldAnncmntDt = value;
    }

    /**
     * Gets the value of the fxgDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getFxgDt() {
        return fxgDt;
    }

    /**
     * Sets the value of the fxgDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setFxgDt(DateFormat19Choice value) {
        this.fxgDt = value;
    }

    /**
     * Gets the value of the ltryDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getLtryDt() {
        return ltryDt;
    }

    /**
     * Sets the value of the ltryDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setLtryDt(DateFormat19Choice value) {
        this.ltryDt = value;
    }

    /**
     * Gets the value of the newMtrtyDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getNewMtrtyDt() {
        return newMtrtyDt;
    }

    /**
     * Sets the value of the newMtrtyDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setNewMtrtyDt(DateFormat19Choice value) {
        this.newMtrtyDt = value;
    }

    /**
     * Gets the value of the mtgDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getMtgDt() {
        return mtgDt;
    }

    /**
     * Sets the value of the mtgDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setMtgDt(DateFormat19Choice value) {
        this.mtgDt = value;
    }

    /**
     * Gets the value of the mrgnFxgDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getMrgnFxgDt() {
        return mrgnFxgDt;
    }

    /**
     * Sets the value of the mrgnFxgDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setMrgnFxgDt(DateFormat19Choice value) {
        this.mrgnFxgDt = value;
    }

    /**
     * Gets the value of the prratnDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getPrratnDt() {
        return prratnDt;
    }

    /**
     * Sets the value of the prratnDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setPrratnDt(DateFormat19Choice value) {
        this.prratnDt = value;
    }

    /**
     * Gets the value of the rcrdDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getRcrdDt() {
        return rcrdDt;
    }

    /**
     * Sets the value of the rcrdDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setRcrdDt(DateFormat19Choice value) {
        this.rcrdDt = value;
    }

    /**
     * Gets the value of the regnDdln property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getRegnDdln() {
        return regnDdln;
    }

    /**
     * Sets the value of the regnDdln property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setRegnDdln(DateFormat19Choice value) {
        this.regnDdln = value;
    }

    /**
     * Gets the value of the rsltsPblctnDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getRsltsPblctnDt() {
        return rsltsPblctnDt;
    }

    /**
     * Sets the value of the rsltsPblctnDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setRsltsPblctnDt(DateFormat19Choice value) {
        this.rsltsPblctnDt = value;
    }

    /**
     * Gets the value of the ddlnToSplt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getDdlnToSplt() {
        return ddlnToSplt;
    }

    /**
     * Sets the value of the ddlnToSplt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setDdlnToSplt(DateFormat19Choice value) {
        this.ddlnToSplt = value;
    }

    /**
     * Gets the value of the ddlnForTaxBrkdwnInstr property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getDdlnForTaxBrkdwnInstr() {
        return ddlnForTaxBrkdwnInstr;
    }

    /**
     * Sets the value of the ddlnForTaxBrkdwnInstr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setDdlnForTaxBrkdwnInstr(DateFormat19Choice value) {
        this.ddlnForTaxBrkdwnInstr = value;
    }

    /**
     * Gets the value of the tradgSspdDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getTradgSspdDt() {
        return tradgSspdDt;
    }

    /**
     * Sets the value of the tradgSspdDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setTradgSspdDt(DateFormat19Choice value) {
        this.tradgSspdDt = value;
    }

    /**
     * Gets the value of the ucondlDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getUcondlDt() {
        return ucondlDt;
    }

    /**
     * Sets the value of the ucondlDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setUcondlDt(DateFormat19Choice value) {
        this.ucondlDt = value;
    }

    /**
     * Gets the value of the whlyUcondlDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getWhlyUcondlDt() {
        return whlyUcondlDt;
    }

    /**
     * Sets the value of the whlyUcondlDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setWhlyUcondlDt(DateFormat19Choice value) {
        this.whlyUcondlDt = value;
    }

    /**
     * Gets the value of the exDvddDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getExDvddDt() {
        return exDvddDt;
    }

    /**
     * Sets the value of the exDvddDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setExDvddDt(DateFormat19Choice value) {
        this.exDvddDt = value;
    }

    /**
     * Gets the value of the offclAnncmntPblctnDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getOffclAnncmntPblctnDt() {
        return offclAnncmntPblctnDt;
    }

    /**
     * Sets the value of the offclAnncmntPblctnDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setOffclAnncmntPblctnDt(DateFormat19Choice value) {
        this.offclAnncmntPblctnDt = value;
    }

    /**
     * Gets the value of the spclExDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getSpclExDt() {
        return spclExDt;
    }

    /**
     * Sets the value of the spclExDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setSpclExDt(DateFormat19Choice value) {
        this.spclExDt = value;
    }

    /**
     * Gets the value of the grntedPrtcptnDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getGrntedPrtcptnDt() {
        return grntedPrtcptnDt;
    }

    /**
     * Sets the value of the grntedPrtcptnDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setGrntedPrtcptnDt(DateFormat19Choice value) {
        this.grntedPrtcptnDt = value;
    }

    /**
     * Gets the value of the elctnToCtrPtyDdln property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getElctnToCtrPtyDdln() {
        return elctnToCtrPtyDdln;
    }

    /**
     * Sets the value of the elctnToCtrPtyDdln property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setElctnToCtrPtyDdln(DateFormat19Choice value) {
        this.elctnToCtrPtyDdln = value;
    }

    /**
     * Gets the value of the lpsdDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getLpsdDt() {
        return lpsdDt;
    }

    /**
     * Sets the value of the lpsdDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setLpsdDt(DateFormat19Choice value) {
        this.lpsdDt = value;
    }

    /**
     * Gets the value of the pmtDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getPmtDt() {
        return pmtDt;
    }

    /**
     * Sets the value of the pmtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setPmtDt(DateFormat19Choice value) {
        this.pmtDt = value;
    }

    /**
     * Gets the value of the thrdPtyDdln property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getThrdPtyDdln() {
        return thrdPtyDdln;
    }

    /**
     * Sets the value of the thrdPtyDdln property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setThrdPtyDdln(DateFormat19Choice value) {
        this.thrdPtyDdln = value;
    }

    /**
     * Gets the value of the earlyThrdPtyDdln property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getEarlyThrdPtyDdln() {
        return earlyThrdPtyDdln;
    }

    /**
     * Sets the value of the earlyThrdPtyDdln property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setEarlyThrdPtyDdln(DateFormat19Choice value) {
        this.earlyThrdPtyDdln = value;
    }

    /**
     * Gets the value of the mktClmTrckgEndDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getMktClmTrckgEndDt() {
        return mktClmTrckgEndDt;
    }

    /**
     * Sets the value of the mktClmTrckgEndDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setMktClmTrckgEndDt(DateFormat19Choice value) {
        this.mktClmTrckgEndDt = value;
    }

    /**
     * Gets the value of the leadPlntffDdln property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat19Choice }
     *     
     */
    public DateFormat19Choice getLeadPlntffDdln() {
        return leadPlntffDdln;
    }

    /**
     * Sets the value of the leadPlntffDdln property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat19Choice }
     *     
     */
    public void setLeadPlntffDdln(DateFormat19Choice value) {
        this.leadPlntffDdln = value;
    }

    /**
     * Gets the value of the filgDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat16Choice }
     *     
     */
    public DateFormat16Choice getFilgDt() {
        return filgDt;
    }

    /**
     * Sets the value of the filgDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat16Choice }
     *     
     */
    public void setFilgDt(DateFormat16Choice value) {
        this.filgDt = value;
    }

    /**
     * Gets the value of the hrgDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateFormat16Choice }
     *     
     */
    public DateFormat16Choice getHrgDt() {
        return hrgDt;
    }

    /**
     * Sets the value of the hrgDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFormat16Choice }
     *     
     */
    public void setHrgDt(DateFormat16Choice value) {
        this.hrgDt = value;
    }

}
