//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.datamodel.xml.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorporateActionOption7Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CorporateActionOption7Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ABST"/>
 *     &lt;enumeration value="AMGT"/>
 *     &lt;enumeration value="BSPL"/>
 *     &lt;enumeration value="BUYA"/>
 *     &lt;enumeration value="CASE"/>
 *     &lt;enumeration value="CASH"/>
 *     &lt;enumeration value="CEXC"/>
 *     &lt;enumeration value="CONN"/>
 *     &lt;enumeration value="CONY"/>
 *     &lt;enumeration value="CTEN"/>
 *     &lt;enumeration value="EXER"/>
 *     &lt;enumeration value="LAPS"/>
 *     &lt;enumeration value="MNGT"/>
 *     &lt;enumeration value="MPUT"/>
 *     &lt;enumeration value="NOAC"/>
 *     &lt;enumeration value="NOQU"/>
 *     &lt;enumeration value="OFFR"/>
 *     &lt;enumeration value="OTHR"/>
 *     &lt;enumeration value="OVER"/>
 *     &lt;enumeration value="PROX"/>
 *     &lt;enumeration value="QINV"/>
 *     &lt;enumeration value="SECU"/>
 *     &lt;enumeration value="SLLE"/>
 *     &lt;enumeration value="SPLI"/>
 *     &lt;enumeration value="PRUN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CorporateActionOption7Code")
@XmlEnum
public enum CorporateActionOption7Code {

    ABST,
    AMGT,
    BSPL,
    BUYA,
    CASE,
    CASH,
    CEXC,
    CONN,
    CONY,
    CTEN,
    EXER,
    LAPS,
    MNGT,
    MPUT,
    NOAC,
    NOQU,
    OFFR,
    OTHR,
    OVER,
    PROX,
    QINV,
    SECU,
    SLLE,
    SPLI,
    PRUN;

    public String value() {
        return name();
    }

    public static CorporateActionOption7Code fromValue(String v) {
        return valueOf(v);
    }

}
