//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.datamodel.xml.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntermediateSecurityDistributionType5Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IntermediateSecurityDistributionType5Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BIDS"/>
 *     &lt;enumeration value="DRIP"/>
 *     &lt;enumeration value="DVCA"/>
 *     &lt;enumeration value="DVOP"/>
 *     &lt;enumeration value="EXRI"/>
 *     &lt;enumeration value="PRIO"/>
 *     &lt;enumeration value="DVSC"/>
 *     &lt;enumeration value="DVSE"/>
 *     &lt;enumeration value="INTR"/>
 *     &lt;enumeration value="LIQU"/>
 *     &lt;enumeration value="SOFF"/>
 *     &lt;enumeration value="SPLF"/>
 *     &lt;enumeration value="BONU"/>
 *     &lt;enumeration value="EXOF"/>
 *     &lt;enumeration value="MRGR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IntermediateSecurityDistributionType5Code")
@XmlEnum
public enum IntermediateSecurityDistributionType5Code {

    BIDS,
    DRIP,
    DVCA,
    DVOP,
    EXRI,
    PRIO,
    DVSC,
    DVSE,
    INTR,
    LIQU,
    SOFF,
    SPLF,
    BONU,
    EXOF,
    MRGR;

    public String value() {
        return name();
    }

    public static IntermediateSecurityDistributionType5Code fromValue(String v) {
        return valueOf(v);
    }

}
