//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.datamodel.xml.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterestComputationMethod2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InterestComputationMethod2Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A001"/>
 *     &lt;enumeration value="A002"/>
 *     &lt;enumeration value="A003"/>
 *     &lt;enumeration value="A004"/>
 *     &lt;enumeration value="A005"/>
 *     &lt;enumeration value="A006"/>
 *     &lt;enumeration value="A007"/>
 *     &lt;enumeration value="A008"/>
 *     &lt;enumeration value="A009"/>
 *     &lt;enumeration value="A010"/>
 *     &lt;enumeration value="A011"/>
 *     &lt;enumeration value="A012"/>
 *     &lt;enumeration value="A013"/>
 *     &lt;enumeration value="A014"/>
 *     &lt;enumeration value="NARR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InterestComputationMethod2Code")
@XmlEnum
public enum InterestComputationMethod2Code {

    @XmlEnumValue("A001")
    A_001("A001"),
    @XmlEnumValue("A002")
    A_002("A002"),
    @XmlEnumValue("A003")
    A_003("A003"),
    @XmlEnumValue("A004")
    A_004("A004"),
    @XmlEnumValue("A005")
    A_005("A005"),
    @XmlEnumValue("A006")
    A_006("A006"),
    @XmlEnumValue("A007")
    A_007("A007"),
    @XmlEnumValue("A008")
    A_008("A008"),
    @XmlEnumValue("A009")
    A_009("A009"),
    @XmlEnumValue("A010")
    A_010("A010"),
    @XmlEnumValue("A011")
    A_011("A011"),
    @XmlEnumValue("A012")
    A_012("A012"),
    @XmlEnumValue("A013")
    A_013("A013"),
    @XmlEnumValue("A014")
    A_014("A014"),
    NARR("NARR");
    private final String value;

    InterestComputationMethod2Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InterestComputationMethod2Code fromValue(String v) {
        for (InterestComputationMethod2Code c: InterestComputationMethod2Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
