//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.datamodel.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonIdentification6 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonIdentification6">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Issr" type="{}Max35Text" minOccurs="0"/>
 *         &lt;element name="PrsnIdTp" type="{}PersonIdentificationType1Choice"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonIdentification6", propOrder = {
    "issr",
    "prsnIdTp"
})
public class PersonIdentification6 {

    @XmlElement(name = "Issr")
    protected String issr;
    @XmlElement(name = "PrsnIdTp", required = true)
    protected PersonIdentificationType1Choice prsnIdTp;

    /**
     * Gets the value of the issr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssr() {
        return issr;
    }

    /**
     * Sets the value of the issr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssr(String value) {
        this.issr = value;
    }

    /**
     * Gets the value of the prsnIdTp property.
     * 
     * @return
     *     possible object is
     *     {@link PersonIdentificationType1Choice }
     *     
     */
    public PersonIdentificationType1Choice getPrsnIdTp() {
        return prsnIdTp;
    }

    /**
     * Sets the value of the prsnIdTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIdentificationType1Choice }
     *     
     */
    public void setPrsnIdTp(PersonIdentificationType1Choice value) {
        this.prsnIdTp = value;
    }

}
