//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.datamodel.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SafekeepingPlaceFormatChoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SafekeepingPlaceFormatChoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Id" type="{}SafekeepingPlaceAsCodeAndPartyIdentification"/>
 *         &lt;element name="IdAsDSS" type="{}GenericIdentification5"/>
 *         &lt;element name="IdAsCtry" type="{}CountryCode"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SafekeepingPlaceFormatChoice", propOrder = {
    "id",
    "idAsDSS",
    "idAsCtry"
})
public class SafekeepingPlaceFormatChoice {

    @XmlElement(name = "Id")
    protected SafekeepingPlaceAsCodeAndPartyIdentification id;
    @XmlElement(name = "IdAsDSS")
    protected GenericIdentification5 idAsDSS;
    @XmlElement(name = "IdAsCtry")
    protected String idAsCtry;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link SafekeepingPlaceAsCodeAndPartyIdentification }
     *     
     */
    public SafekeepingPlaceAsCodeAndPartyIdentification getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link SafekeepingPlaceAsCodeAndPartyIdentification }
     *     
     */
    public void setId(SafekeepingPlaceAsCodeAndPartyIdentification value) {
        this.id = value;
    }

    /**
     * Gets the value of the idAsDSS property.
     * 
     * @return
     *     possible object is
     *     {@link GenericIdentification5 }
     *     
     */
    public GenericIdentification5 getIdAsDSS() {
        return idAsDSS;
    }

    /**
     * Sets the value of the idAsDSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericIdentification5 }
     *     
     */
    public void setIdAsDSS(GenericIdentification5 value) {
        this.idAsDSS = value;
    }

    /**
     * Gets the value of the idAsCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdAsCtry() {
        return idAsCtry;
    }

    /**
     * Sets the value of the idAsCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdAsCtry(String value) {
        this.idAsCtry = value;
    }

}
