//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.datamodel.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SafekeepingPlaceAsCodeAndPartyIdentification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SafekeepingPlaceAsCodeAndPartyIdentification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PlcSfkpg" type="{}SafekeepingPlace1Code"/>
 *         &lt;element name="Nrrtv" type="{}Max35Text" minOccurs="0"/>
 *         &lt;element name="Pty" type="{}PartyIdentification3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SafekeepingPlaceAsCodeAndPartyIdentification", propOrder = {
    "plcSfkpg",
    "nrrtv",
    "pty"
})
public class SafekeepingPlaceAsCodeAndPartyIdentification {

    @XmlElement(name = "PlcSfkpg", required = true)
    protected SafekeepingPlace1Code plcSfkpg;
    @XmlElement(name = "Nrrtv")
    protected String nrrtv;
    @XmlElement(name = "Pty")
    protected PartyIdentification3 pty;

    /**
     * Gets the value of the plcSfkpg property.
     * 
     * @return
     *     possible object is
     *     {@link SafekeepingPlace1Code }
     *     
     */
    public SafekeepingPlace1Code getPlcSfkpg() {
        return plcSfkpg;
    }

    /**
     * Sets the value of the plcSfkpg property.
     * 
     * @param value
     *     allowed object is
     *     {@link SafekeepingPlace1Code }
     *     
     */
    public void setPlcSfkpg(SafekeepingPlace1Code value) {
        this.plcSfkpg = value;
    }

    /**
     * Gets the value of the nrrtv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrrtv() {
        return nrrtv;
    }

    /**
     * Sets the value of the nrrtv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrrtv(String value) {
        this.nrrtv = value;
    }

    /**
     * Gets the value of the pty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentification3 }
     *     
     */
    public PartyIdentification3 getPty() {
        return pty;
    }

    /**
     * Sets the value of the pty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentification3 }
     *     
     */
    public void setPty(PartyIdentification3 value) {
        this.pty = value;
    }

}
