//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 03:58:45 PM GMT+03:00 
//


package uk.dsxt.voting.common.datamodel.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XtnsnMtngAthrty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XtnsnMtngAthrty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{}PartyIdentification42"/>
 *         &lt;element name="AthrRole" type="{}AuthorityRoleCode"/>
 *         &lt;element name="Pstn" type="{}Max140Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XtnsnMtngAthrty", propOrder = {
    "id",
    "athrRole",
    "pstn"
})
public class XtnsnMtngAthrty {

    @XmlElement(name = "Id", required = true)
    protected PartyIdentification42 id;
    @XmlElement(name = "AthrRole", required = true)
    protected AuthorityRoleCode athrRole;
    @XmlElement(name = "Pstn")
    protected String pstn;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentification42 }
     *     
     */
    public PartyIdentification42 getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentification42 }
     *     
     */
    public void setId(PartyIdentification42 value) {
        this.id = value;
    }

    /**
     * Gets the value of the athrRole property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorityRoleCode }
     *     
     */
    public AuthorityRoleCode getAthrRole() {
        return athrRole;
    }

    /**
     * Sets the value of the athrRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorityRoleCode }
     *     
     */
    public void setAthrRole(AuthorityRoleCode value) {
        this.athrRole = value;
    }

    /**
     * Gets the value of the pstn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPstn() {
        return pstn;
    }

    /**
     * Sets the value of the pstn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPstn(String value) {
        this.pstn = value;
    }

}
